### PR TITLE
Date picker

### PR DESCRIPTION
**Pull request by dodosoya**
Demo:

image

image

https://github.com/cvicream/cv-icream/assets/16853417/aa7f4f5a-f8d4-42ff-8fdd-c7ba0b0e292e

### CODE REVIEW

**Comment by Shan-29** [comment]
可以加一個分隔線把Date Picker的icon跟大家分開嗎？（因為感覺是不同功能的東西）感謝！

Screenshot 2023-12-12 at 13 09 39

**Comment by Shan-29** [comment]
也麻煩加一個Tooltip，讓使用者hover的時候就知道那是什麼～

Screenshot 2023-12-12 at 13 10 43

**Comment by Shan-29** [comment]
想要討論一下 “Currently in this role"的做法～不確定下面這個UI的方法好不好做，不好做的話請再提出，感謝！

Screenshot 2023-12-12 at 13 13 01

**Review by cvicream — APPROVED** [review]

**Comment by agnuschan** [comment]
The starting year would be disappeared when the edit section is a bit narrow.  I have tried to scroll up but still can't see the year.


https://github.com/cvicream/cv-icream/assets/30631048/a9e7e03f-92c5-440a-8a7c-7f54d93b4c85

**Comment by agnuschan** [comment]
Not sure if necessary to keep the date picker button at Description section

CleanShot 2023-12-19 at 01 53 00@2x

**Pull request merged**
