### PR TITLE
✨💄Feature/add note

### PR DESCRIPTION
**Pull request by liuqadnyc**
- store notes in `noteList: Note[]`
```
export interface Note {
  id: number
  location: {
    left: number
    top: number
  }
  value: string
}
```

### CODE REVIEW

**Comment by liuqadnyc** [comment]
- 新增在可拖拉區塊上會有問題
- 修勾勾尾巴
- 點擊新增note icon之後icon維持active status並進入新增模式，直到再點一次就會取消新增模式並取消active status

**Comment by Shan-29** [comment]
Undo behaviour - 
If users delete the note, they can have it back by clicking Undo icon.

**Comment by Shan-29** [comment]
Please can we allow users to create a new note on the whole Preview area (even outside the CV itself)

Screenshot 2023-08-24 at 19 39 43

**Comment by Shan-29** [comment]
The "V" icon is not always clickable. Please see the attached video.

https://github.com/cvicream/cv-icream/assets/68609691/c3a1213c-e9c5-48ff-8459-c579c727eddb

**Comment by Shan-29** [comment]
The Notes don't have to follow the zoom in/out rule - Please can we keep the size always the same. Thank you!

Screenshot 2023-09-01 at 22 42 11

**Comment by Shan-29** [comment]
Please can we remove the blue stroke - It showed when the icon was active and then I pressed the spacebar.

Screenshot 2023-09-01 at 22 42 00

**Comment by Shan-29** [comment]
The Note doesn't really work on mobile phone. (Please see the attached video)


https://github.com/cvicream/cv-icream/assets/68609691/a77a743d-5cbb-4380-84d2-7b87379d5958

**Comment by liuqadnyc** [comment]
> 


Uploading Screen Recording 2023-09-05 at 17.04.52.mov…

**Comment by liuqadnyc** [comment]
> Please can we allow users to create a new note on the whole Preview area (even outside the CV itself)
> 
> Screenshot 2023-08-24 at 19 39 43

this is before

https://github.com/cvicream/cv-icream/assets/34543459/67db5233-3482-4984-9a2b-f31846373d13

this is after  I fix the note to outside of CV

https://github.com/cvicream/cv-icream/assets/34543459/b931bbad-7ea2-4c39-a636-a0842218f945

In video you can see note's location depends on  screen size, so I think we probably have to limit note location in the CV.

**Comment by liuqadnyc** [comment]
> Please can we remove the blue stroke - It showed when the icon was active and then I pressed the spacebar.
> 
> Screenshot 2023-09-01 at 22 42 00

this is design for when you only have keyboard, it happens in every selectable element so I don't think we should remove it

**Comment by liuqadnyc** [comment]
create note之後解除adding mode，且focus在note

**Comment by AmberYYH** [comment]
Mobile version's behaviour and UI are not very stable in this version (please see the recording) 
- The UI is not in the right place for the preview area
- I can't find the note being added ( it disappeared after I added it, the suddenly appear)
- and the "scrolling" behaviour seems like I can infinite scrolling? 
63E5B667-0D79-4B9D-BAA4-C681266B2E30_1_102_o

**Comment by AmberYYH** [comment]
Web testing
Screenshot 2023-09-09 at 20 29 51
I think this is the one you mentioned.

**Comment by AmberYYH** [comment]
Web testing

55749FEF-0655-498D-8023-E4B7B033CD44_1_102_o

- The note will be got covered up by the editing tool bar partly if I make a note on the bottom. (or make the note too long)

**Comment by AmberYYH** [comment]
Web testing


https://github.com/cvicream/cv-icream/assets/143964615/0827aacf-12e9-482f-b77e-2539daa28ff0

**Comment by liuqadnyc** [comment]
> Web testing
> 
> 55749FEF-0655-498D-8023-E4B7B033CD44_1_102_o
> 
> * The note will be got covered up by the editing tool bar partly if I make a note on the bottom. (or make the note too long)

Do you have some  ideas on it? I feel like we shouldn't let note covers toolbar since it's quiet important and also toolbar can collapse.

**Comment by liuqadnyc** [comment]
> Web testing
> 
>  Screen.Recording.2023-09-09.at.22.08.48-1.mov

What's this one about?

**Comment by liuqadnyc** [comment]
> Web testing
> 
>  Screen.Recording.2023-09-09.at.22.08.48-1.mov

What is this about?

**Comment by liuqadnyc** [comment]
> * " behaviour seems like I can infinite scrolling?

You probably need to upload video again since it's just screenshot.

**Comment by AmberYYH** [comment]
> > Web testing
> > 55749FEF-0655-498D-8023-E4B7B033CD44_1_102_o
> > 
> > * The note will be got covered up by the editing tool bar partly if I make a note on the bottom. (or make the note too long)
> 
> Do you have some ideas on it? I feel like we shouldn't let note covers toolbar since it's quiet important and also toolbar can collapse.

Would it be possible for the note to open upward when we add the note on the bottom of the CV? and vice versa 
Open downward when adding the note on the top of the CV.  
Open the left side when adding the note on the right side of the CV. vice versa

Screenshot 2023-09-10 at 03 21 17

**Comment by Shan-29** [comment]
1. 我剛剛把寫好的Note移動位置，不確定中間是不是發生什麼事，但總之和錄影裡面的一樣，這個Note就打不開了（不知道是不是跟那個Section重疊有關）

不過這個可以work around，我後來再新增一個Note，原本的Note就可以打開了

https://github.com/cvicream/cv-icream/assets/68609691/531ec353-7489-4e2c-ac00-1c43e7197c57

**Comment by Shan-29** [comment]
2. 以下這個現象很有趣，就是Note打開的時候如果移動位置，Note的icon和box會有點像跳交際舞一樣左右換位置，所以有點難移到我想要Note去的定點

不過我覺得目前這個也不影響主功能

https://github.com/cvicream/cv-icream/assets/68609691/d4b651c9-21b7-47b5-a6ce-0ec94b15a84b

**Comment by Shan-29** [comment]
3. Undo部分： 

(1) 如果我刪掉Note，沒辦法Undo回來。
(2) Note 打開, undo 時還是會卡住（就是怎麼按Undo鍵都沒有反應），不過這也是比較edge case

**Comment by Shan-29** [comment]
4. 如果本來筆記內有文字，手動清空後還沒儲存，點旁邊Note也會直接消失（因為我可能還在編輯裡面的字）

不過我覺得這也是edge case

https://github.com/cvicream/cv-icream/assets/68609691/e9300037-5294-404a-bc8a-b1e1289903d7

**Comment by Shan-29** [comment]
5. 請問可以偵測ipad時也把Note拿掉嗎？
（如果不好做也沒關係）

**Comment by liuqadnyc** [comment]
> 2. 以下這個現象很有趣，就是Note打開的時候如果移動位置，Note的icon和box會有點像跳交際舞一樣左右換位置，所以有點難移到我想要Note去的定點
> 
> 不過我覺得目前這個也不影響主功能
> 
>  Screen.Recording.2023-09-11.at.00.26.22.mov

我之前不小心把draggable設到全部元件但我覺得放在icon上就好(不然note裡如果要選取字會變拖曳)，這樣應該順便可以解決你這個問題


https://github.com/cvicream/cv-icream/assets/34543459/c50310fd-9332-457d-b67c-b4463fd3e21d

**Comment by liuqadnyc** [comment]
> 1. 的Note移動位置，不確定中間是不是發生什麼事，但總之和錄影裡面的一樣，這個Note就打不開了（不知道是不是跟那個Section

這個再麻煩看看中間是發生了什麼事我們才能重現，謝謝～

**Comment by liuqadnyc** [comment]
> 3. Undo部分：
> 
> (1) 如果我刪掉Note，沒辦法Undo回來。 (2) Note 打開, undo 時還是會卡住（就是怎麼按Undo鍵都沒有反應），不過這也是比較edge case

這目前真的沒什麼想法， @dodosoya 可以幫我看看嗎？

**Review by cvicream — APPROVED** [review]

**Pull request merged**
