### PR TITLE
Editable block

### PR DESCRIPTION
**Pull request by dodosoya**
## What's included?
Make blocks editable.

image

## Need changes
- [x] Remove the moving icon.
- [x] Show the resizer when hovering.
- [x] Do not show the resizer on the CV preview.
- [x] Store the changed width in the draft file.

### CODE REVIEW

**Comment by Shan-29** [comment]
Please can we have the max/min width for the Contact area and the Side bar area as followers:

Min width: 
Please set the original width as the min (Users can only make it bigger, but not smaller than the original setting)

Max width:
Please set the max width for the Side bar to the half of the Main content area (See the attached image)

Thank you!

Screenshot 2023-09-01 at 21 47 22

Screenshot 2023-09-01 at 22 02 08

**Comment by Shan-29** [comment]
Please can we make the Name & Title area align to the Side bar area (Please see attached images). Thank you!

Screenshot 2023-09-01 at 21 50 06

Screenshot 2023-09-01 at 21 50 31

**Comment by Shan-29** [comment]
Please can we have the adjustment line appearing with the colour background while hovering the whole area. Just thought it might help users to notice it. Thank you!

Screenshot 2023-09-01 at 21 54 53

**Comment by dodosoya** [comment]
> Please can we have the max/min width for the Contact area and the Side bar area as followers:
> 
> Min width: Please set the original width as the min (Users can only make it bigger, but not smaller than the original setting)
> 
> Max width: Please set the max width for the Side bar to the half of the Main content area (See the attached image)
> 
> Thank you!
> 
> Screenshot 2023-09-01 at 21 47 22 Screenshot 2023-09-01 at 22 02 08

Min width is applied which is 25%.

**Review by cvicream — APPROVED** [review]

**Pull request merged**
