### PR TITLE
Zoom in out improvements

### PR DESCRIPTION
**Pull request by dodosoya**
## Design

image

Max scale: 300%
Min scale: 25%
Zoom in/out step: twice/half

### CODE REVIEW

**Comment by Shan-29** [comment]
Please can we change the hot key for Zoom in/out into only +/-. Thank you!

**Comment by Shan-29** [comment]
The touch gesture on Mac for Zoom in/out is a bit too sensitive - If I use two fingers to enlarge the screen, the size will be straight away to 300%. Same as when I try to use two fingers to make the size smaller.

Can we make it less sensitive? Thank you!



https://github.com/cvicream/cv-icream/assets/68609691/582122af-c097-4c58-b1d4-d1fad192b9c7

**Comment by Shan-29** [comment]
Not sure why. But there is a blue stroke around the icon. Can we remove it please. Thank you!
Screenshot 2023-09-02 at 20 20 48

**Comment by Shan-29** [comment]
For mobile version - 
Can we also apply to fit the screen when users double-click the %? Thank you!

**Comment by Shan-29** [comment]
For mobile version - 
Can we remove the round corner for the background while editing please? - It looks nice with the round corner, but just thought we can make the UI consistent of editing mode across the platform. Thank you!

S__27516989

**Review by cvicream — APPROVED** [review]

**Pull request merged**
